import type {
  Sermon,
  Event,
  Category,
  DonationCampaign,
  SpiritualResource,
  Hymn,
  RadioStation,
  LiveStream,
  MediaFile,
  User,
} from "./types";

const CHURCH_ID = "church-001";
const NOW = new Date();

const formatDate = (date: Date) => date.toISOString();
const addDays = (days: number) => new Date(NOW.getTime() + days * 24 * 60 * 60 * 1000);
const addHours = (hours: number) => new Date(NOW.getTime() + hours * 60 * 60 * 1000);

export const sermons: Sermon[] = [
  {
    id: "srm-001",
    church_id: CHURCH_ID,
    title: "Faith in the Midst of Uncertainty",
    slug: "faith-in-uncertainty",
    description: "A powerful sermon about trusting God during difficult times.",
    speaker: "Pastor James Mitchell",
    series: "Faith Series",
    duration_minutes: 42,
    video_url: "https://example.com/video/sermon-001.mp4",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Sermon+001",
    status: "active",
    published_date: formatDate(NOW),
    sermon_date: formatDate(addDays(-7)),
    views_count: 1240,
    created_at: formatDate(addDays(-30)),
    updated_at: formatDate(NOW),
  },
  {
    id: "srm-002",
    church_id: CHURCH_ID,
    title: "The Power of Prayer",
    slug: "power-of-prayer",
    description: "Exploring the transformative power of consistent prayer in our lives.",
    speaker: "Pastor Sarah Williams",
    series: "Spiritual Growth",
    duration_minutes: 38,
    video_url: "https://example.com/video/sermon-002.mp4",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Sermon+002",
    status: "active",
    published_date: formatDate(addDays(-14)),
    sermon_date: formatDate(addDays(-14)),
    views_count: 2156,
    created_at: formatDate(addDays(-45)),
    updated_at: formatDate(addDays(-14)),
  },
  {
    id: "srm-003",
    church_id: CHURCH_ID,
    title: "Living Out the Great Commandment",
    slug: "great-commandment",
    description: "How we can love God and love our neighbors in practical ways.",
    speaker: "Pastor David Johnson",
    series: "Kingdom Values",
    duration_minutes: 45,
    video_url: "https://example.com/video/sermon-003.mp4",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Sermon+003",
    status: "inactive",
    published_date: "",
    sermon_date: formatDate(addDays(7)),
    views_count: 0,
    created_at: formatDate(addDays(-10)),
    updated_at: formatDate(NOW),
  },
  {
    id: "srm-004",
    church_id: CHURCH_ID,
    title: "Resurrection Hope",
    slug: "resurrection-hope",
    description: "Understanding the significance of Christ's resurrection in our faith.",
    speaker: "Pastor James Mitchell",
    series: "Easter Series",
    duration_minutes: 51,
    video_url: "https://example.com/video/sermon-004.mp4",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Sermon+004",
    status: "active",
    published_date: formatDate(addDays(14)),
    sermon_date: formatDate(addDays(14)),
    views_count: 0,
    created_at: formatDate(addDays(-5)),
    updated_at: formatDate(NOW),
  },
];

export const events: Event[] = [
  {
    id: "evt-001",
    church_id: CHURCH_ID,
    title: "Sunday Worship Service",
    slug: "sunday-worship",
    description: "Weekly gathering for praise, worship, and biblical teaching.",
    event_date: formatDate(addDays(3)),
    event_time: "10:00 AM",
    end_time: "11:30 AM",
    location: "Main Sanctuary",
    organizer: "Worship Team",
    max_attendees: 500,
    current_attendees: 342,
    status: "active",
    image_url: "https://via.placeholder.com/400x300?text=Sunday+Service",
    is_virtual: true,
    virtual_link: "https://zoom.us/j/123456789",
    created_at: formatDate(addDays(-60)),
    updated_at: formatDate(NOW),
  },
  {
    id: "evt-002",
    church_id: CHURCH_ID,
    title: "Women's Fellowship Lunch",
    slug: "womens-fellowship",
    description: "Monthly gathering of women for fellowship, prayer, and community.",
    event_date: formatDate(addDays(10)),
    event_time: "12:00 PM",
    end_time: "2:00 PM",
    location: "Fellowship Hall",
    organizer: "Women's Ministry",
    max_attendees: 80,
    current_attendees: 45,
    status: "active",
    image_url: "https://via.placeholder.com/400x300?text=Womens+Lunch",
    is_virtual: false,
    created_at: formatDate(addDays(-45)),
    updated_at: formatDate(NOW),
  },
  {
    id: "evt-003",
    church_id: CHURCH_ID,
    title: "Youth Summer Camp",
    slug: "youth-summer-camp",
    description: "Week-long spiritual development camp for teens aged 13-18.",
    event_date: formatDate(addDays(45)),
    event_time: "8:00 AM",
    end_time: "5:00 PM",
    location: "Mountain Retreat Center",
    organizer: "Youth Ministry",
    max_attendees: 150,
    current_attendees: 87,
    status: "inactive",
    image_url: "https://via.placeholder.com/400x300?text=Youth+Camp",
    is_virtual: false,
    created_at: formatDate(addDays(-20)),
    updated_at: formatDate(NOW),
  },
];

export const categories: Category[] = [
  {
    id: "cat-001",
    church_id: CHURCH_ID,
    name: "Sermons",
    slug: "sermons",
    description: "Sunday messages and teaching series",
    icon: "book-open",
    color: "#1B73E8",
    order: 1,
    status: "active",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-120)),
  },
  {
    id: "cat-002",
    church_id: CHURCH_ID,
    name: "Bible Studies",
    slug: "bible-studies",
    description: "Topical and book studies of Scripture",
    icon: "book",
    color: "#059669",
    order: 2,
    status: "active",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-120)),
  },
  {
    id: "cat-003",
    church_id: CHURCH_ID,
    name: "Prayer Guides",
    slug: "prayer-guides",
    description: "Resources for guided and intercessory prayer",
    icon: "hands-praying",
    color: "#7c3aed",
    order: 3,
    status: "active",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-120)),
  },
  {
    id: "cat-004",
    church_id: CHURCH_ID,
    name: "Testimonies",
    slug: "testimonies",
    description: "Faith stories from our church community",
    icon: "heart",
    color: "#DC2626",
    order: 4,
    status: "active",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-120)),
  },
  {
    id: "cat-005",
    church_id: CHURCH_ID,
    name: "Devotionals",
    slug: "devotionals",
    description: "Daily devotional thoughts and reflections",
    icon: "moon",
    color: "#F59E0B",
    order: 5,
    status: "active",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-120)),
  },
];

export const donationCampaigns: DonationCampaign[] = [
  {
    id: "camp-001",
    church_id: CHURCH_ID,
    title: "Building Fund Campaign",
    slug: "building-fund",
    description: "Raising funds for our new fellowship building expansion.",
    goal_amount: 250000,
    current_amount: 187450,
    start_date: formatDate(addDays(-60)),
    end_date: formatDate(addDays(60)),
    status: "active",
    campaign_type: "building",
    image_url: "https://via.placeholder.com/400x300?text=Building+Fund",
    donation_count: 342,
    created_at: formatDate(addDays(-90)),
    updated_at: formatDate(NOW),
  },
  {
    id: "camp-002",
    church_id: CHURCH_ID,
    title: "Missions Outreach",
    slug: "missions-outreach",
    description: "Supporting missionary work and community outreach programs globally.",
    goal_amount: 50000,
    current_amount: 38920,
    start_date: formatDate(addDays(-30)),
    end_date: formatDate(addDays(90)),
    status: "active",
    campaign_type: "missions",
    image_url: "https://via.placeholder.com/400x300?text=Missions",
    donation_count: 128,
    created_at: formatDate(addDays(-60)),
    updated_at: formatDate(NOW),
  },
  {
    id: "camp-003",
    church_id: CHURCH_ID,
    title: "Youth Scholarships",
    slug: "youth-scholarships",
    description: "Educational scholarships for youth in our congregation.",
    goal_amount: 30000,
    current_amount: 12500,
    start_date: formatDate(addDays(7)),
    end_date: formatDate(addDays(120)),
    status: "inactive",
    campaign_type: "education",
    image_url: "https://via.placeholder.com/400x300?text=Scholarships",
    donation_count: 0,
    created_at: formatDate(addDays(-10)),
    updated_at: formatDate(NOW),
  },
];

export const spiritualResources: SpiritualResource[] = [
  {
    id: "res-001",
    church_id: CHURCH_ID,
    title: "Daily Devotional: Walking with Jesus",
    slug: "daily-devotional-walking",
    description: "A 30-day devotional journey exploring discipleship and faith.",
    content: "Day 1: Understanding what it truly means to follow Jesus...",
    category_id: "cat-005",
    author: "Rev. Michael Anderson",
    resource_type: "devotional",
    status: "active",
    published_date: formatDate(addDays(-15)),
    view_count: 542,
    created_at: formatDate(addDays(-45)),
    updated_at: formatDate(addDays(-15)),
  },
  {
    id: "res-002",
    church_id: CHURCH_ID,
    title: "Prayer Guide: Intercessory Prayer",
    slug: "prayer-guide-intercession",
    description: "A comprehensive guide to praying for others and the world.",
    content: "Intercessory prayer is standing in the gap for others...",
    category_id: "cat-003",
    author: "Pastor Sarah Williams",
    resource_type: "prayer_guide",
    status: "active",
    published_date: formatDate(addDays(-30)),
    view_count: 387,
    created_at: formatDate(addDays(-60)),
    updated_at: formatDate(addDays(-30)),
  },
  {
    id: "res-003",
    church_id: CHURCH_ID,
    title: "Understanding Grace",
    slug: "understanding-grace",
    description: "Exploring the theological concept of God's grace in daily life.",
    content: "Grace is God's unmerited favor toward humanity...",
    category_id: "cat-001",
    author: "Dr. James Mitchell",
    resource_type: "study",
    status: "inactive",
    published_date: "",
    view_count: 0,
    created_at: formatDate(addDays(-5)),
    updated_at: formatDate(NOW),
  },
];

export const hymns: Hymn[] = [
  {
    id: "hymn-001",
    church_id: CHURCH_ID,
    title: "Amazing Grace",
    slug: "amazing-grace",
    lyrics: "Amazing grace, how sweet the sound...",
    composer: "John Newton",
    hymn_number: "1",
    key: "G Major",
    tempo: "Moderately Slow",
    status: "active",
    audio_url: "https://example.com/audio/amazing-grace.mp3",
    midi_url: "https://example.com/midi/amazing-grace.mid",
    created_at: formatDate(addDays(-90)),
    updated_at: formatDate(addDays(-90)),
  },
  {
    id: "hymn-002",
    church_id: CHURCH_ID,
    title: "Jesus Loves Me",
    slug: "jesus-loves-me",
    lyrics: "Jesus loves me, this I know...",
    composer: "Anna Bartlett Warner",
    hymn_number: "2",
    key: "C Major",
    status: "active",
    audio_url: "https://example.com/audio/jesus-loves-me.mp3",
    created_at: formatDate(addDays(-90)),
    updated_at: formatDate(addDays(-90)),
  },
  {
    id: "hymn-003",
    church_id: CHURCH_ID,
    title: "It Is Well with My Soul",
    slug: "it-is-well",
    lyrics: "When peace like a river attendeth my way...",
    composer: "Horatio Spafford",
    hymn_number: "3",
    key: "D Major",
    tempo: "Moderately",
    status: "active",
    audio_url: "https://example.com/audio/it-is-well.mp3",
    midi_url: "https://example.com/midi/it-is-well.mid",
    created_at: formatDate(addDays(-90)),
    updated_at: formatDate(addDays(-90)),
  },
];

export const radioStations: RadioStation[] = [
  {
    id: "radio-001",
    church_id: CHURCH_ID,
    name: "Grace Radio Station",
    slug: "grace-radio",
    description: "24/7 Christian music and teachings",
    stream_url: "https://stream.example.com/grace-radio",
    status: "active",
    frequency: "FM 104.3",
    is_live: true,
    current_program: "Morning Praise",
    listeners_count: 2341,
    created_at: formatDate(addDays(-180)),
    updated_at: formatDate(NOW),
  },
  {
    id: "radio-002",
    church_id: CHURCH_ID,
    name: "Family Worship Radio",
    slug: "family-worship-radio",
    description: "Family-friendly Christian programming",
    stream_url: "https://stream.example.com/family-worship",
    status: "active",
    frequency: "AM 890",
    is_live: false,
    current_program: "Archived Content",
    listeners_count: 1204,
    created_at: formatDate(addDays(-150)),
    updated_at: formatDate(NOW),
  },
];

export const liveStreams: LiveStream[] = [
  {
    id: "live-001",
    church_id: CHURCH_ID,
    title: "Sunday Morning Worship",
    slug: "sunday-morning-worship",
    description: "Live worship service from our main sanctuary",
    stream_url: "https://youtube.com/watch?v=live-001",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Sunday+Live",
    status: "live",
    start_time: formatDate(addHours(1)),
    viewers_count: 1523,
    platform: "youtube",
    created_at: formatDate(NOW),
    updated_at: formatDate(NOW),
  },
  {
    id: "live-002",
    church_id: CHURCH_ID,
    title: "Prayer Meeting",
    slug: "prayer-meeting-live",
    description: "Community prayer gathering",
    stream_url: "https://facebook.com/live/prayer-meeting",
    thumbnail_url: "https://via.placeholder.com/320x180?text=Prayer+Meeting",
    status: "active",
    start_time: formatDate(addDays(2)),
    viewers_count: 0,
    platform: "facebook",
    created_at: formatDate(NOW),
    updated_at: formatDate(NOW),
  },
];

export const mediaFiles: MediaFile[] = [
  {
    id: "media-001",
    church_id: CHURCH_ID,
    title: "Sermon Video - Faith Series Part 1",
    file_name: "faith-sermon-001.mp4",
    file_type: "video",
    file_size: 524288000,
    mime_type: "video/mp4",
    url: "https://cdn.example.com/videos/faith-sermon-001.mp4",
    duration_seconds: 2520,
    width: 1920,
    height: 1080,
    status: "active",
    uploaded_by: "admin@church.com",
    created_at: formatDate(addDays(-30)),
    updated_at: formatDate(addDays(-30)),
  },
  {
    id: "media-002",
    church_id: CHURCH_ID,
    title: "Worship Music Background",
    file_name: "worship-bg.mp3",
    file_type: "audio",
    file_size: 8388608,
    mime_type: "audio/mpeg",
    url: "https://cdn.example.com/audio/worship-bg.mp3",
    duration_seconds: 300,
    status: "active",
    uploaded_by: "music@church.com",
    created_at: formatDate(addDays(-45)),
    updated_at: formatDate(addDays(-45)),
  },
  {
    id: "media-003",
    church_id: CHURCH_ID,
    title: "Church Logo",
    file_name: "church-logo.png",
    file_type: "image",
    file_size: 262144,
    mime_type: "image/png",
    url: "https://cdn.example.com/images/church-logo.png",
    width: 500,
    height: 500,
    status: "active",
    uploaded_by: "design@church.com",
    created_at: formatDate(addDays(-90)),
    updated_at: formatDate(addDays(-90)),
  },
  {
    id: "media-004",
    church_id: CHURCH_ID,
    title: "Event Poster - Summer Camp",
    file_name: "summer-camp-poster.jpg",
    file_type: "image",
    file_size: 1048576,
    mime_type: "image/jpeg",
    url: "https://cdn.example.com/images/summer-camp-poster.jpg",
    width: 800,
    height: 600,
    status: "active",
    uploaded_by: "youth@church.com",
    created_at: formatDate(addDays(-15)),
    updated_at: formatDate(addDays(-15)),
  },
];

export const users: User[] = [
  {
    id: "user-001",
    church_id: CHURCH_ID,
    name: "Grace Anderson",
    email: "grace@church.com",
    role: "admin",
    status: "active",
    last_login: formatDate(NOW),
    avatar_url: "https://via.placeholder.com/40x40?text=GA",
    phone: "+1 (555) 123-4567",
    created_at: formatDate(addDays(-180)),
    updated_at: formatDate(NOW),
  },
  {
    id: "user-002",
    church_id: CHURCH_ID,
    name: "James Mitchell",
    email: "james@church.com",
    role: "editor",
    status: "active",
    last_login: formatDate(addDays(-1)),
    avatar_url: "https://via.placeholder.com/40x40?text=JM",
    phone: "+1 (555) 234-5678",
    created_at: formatDate(addDays(-150)),
    updated_at: formatDate(addDays(-1)),
  },
  {
    id: "user-003",
    church_id: CHURCH_ID,
    name: "Sarah Williams",
    email: "sarah@church.com",
    role: "moderator",
    status: "active",
    last_login: formatDate(addDays(-3)),
    avatar_url: "https://via.placeholder.com/40x40?text=SW",
    created_at: formatDate(addDays(-120)),
    updated_at: formatDate(addDays(-3)),
  },
];
